#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/apache2
- name: update apt cache & install {{ apache2_package_name }}
  apt:
    update_cache: yes
    name: "{{ apache2_package_name }}"
    state: present

- name: enable and start {{ apache2_service_name }}
  service:
    name: "{{ apache2_service_name }}"
    state: started
    enabled: yes

- name: create index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: allow 'Apache Full' in ufw
  ufw:
    rule: allow
    name: 'Apache Full'
